### ISSUE TITLE
Enable multi-arch container image build (build-docker-image)

### ISSUE THREAD

**Issue by leiicamundi** [camunda/infra-global-github-actions#165]
#### Problem
Our current GitHub Action (`docker/build-push-action@v5`) lacks multi-architecture support, limiting deployment to various production platforms.

#### Context
Referencing [Issue #40](https://github.com/camunda/team-infrastructure-experience/issues/40), our project infrastructure requires multi-arch images for broader platform compatibility.

#### Request
Enhance the action by integrating QEMU for multi-architecture support. Proposed workflow snippet:

```yaml
# ... (existing workflow)

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      id: build-push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7  # Add desired platforms

# ... (rest of the workflow)
```

#### Impact
Facilitating multi-arch builds improves deployment flexibility across diverse platforms.
