### ISSUE TITLE
Python Installation Failure on ARM Architecture

### ISSUE THREAD

**Issue by leiicamundi** [camunda/infra-global-github-actions#167]
### Problem
Encountered a Python installation failure when using AWS ARM runners for self-hosted workflows.

### Description
While configuring self-hosted runners, I opted to use AWS ARM runners scheduled on arm64 nodes.

However, during the setup process, I encountered a Python installation failure with the following error:

```
The version '3.12' with architecture 'arm64' was not found for Ubuntu 20.04.
```

### Solution
The recommended solution is to use deadsnakes for ARM, as demonstrated in the following workflow snippet:

```yaml
- name: Install Python3 (ubuntu-arm install)
  uses: deadsnakes/action@3.1.0
  # actions/setup-python doesn't yet support ARM, see https://github.com/actions/setup-python/issues/108#issuecomment-1756948951
  if: ${{ matrix.os == 'ubuntu-arm' }}
```

**Note:** This solution is currently the only available option until official ARM support for Linux is provided by `actions/setup-python`. Refer to [Issue #108](https://github.com/actions/setup-python/issues/108) for ongoing discussions on ARM support.

### Impact
This Python installation issue is particularly noticeable when using AWS ARM runners for self-hosted workflows, we also need to test it on arm runners.
